<?php
// Automatically Generated by TestLink Installer - Wed, 03 Sep 25 21:18:36 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '192.168.56.1');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
